---
version: "3.8"

services:
  echo-ws:
    image: node:18.9.0-alpine
    working_dir: /srv
    command: npm run dev
    ports:
      - "8080:8080"
    volumes:
      - ./.:/srv
    environment:
      NODE_PORT: 8080
